### ISSUE TITLE
[2.1.0] unable to use the Mod Archive

### ISSUE THREAD

**Issue by marcin-szalski** [jllodra/cmod3#10] opened 2016-07-08 10:11 UTC
with the 2.1.0 version I'm unable to download any items from the Mod Archive tab, it's loading all the time.

OS: OS X, 10.11.5

release downloaded from the following location: https://github.com/jllodra/cmod3/releases/download/2.1.0/cmod3-2.1.0-osx64.zip

screenshot attached

<img width="642" alt="screen shot 2016-07-08 at 10 44 49" src="https://cloud.githubusercontent.com/assets/12157682/16684364/a23886c0-44fc-11e6-8183-3f5f3fe2a1b8.png">

**Comment by jllodra** [comment] 2016-07-08 10:16
Thank you for the report Marcin,

will have a look at it as soon as possible and will get back to you.

**Comment by jllodra** [comment] 2016-07-08 10:26
I can't reproduce the problem here... So the problem is elsewhere.

Could you please take a look at the Console Tab? Here are the steps you can follow:

1) Open cmod3
2) Hit Ctrl-0
3) Go to the Console tab
4) Hit Command-r (cmod will reload)
5) Go to the Modarchive tab, etc, till the error happens, and send me an screenshot of your Console. It should contain one or more errors.

**Comment by marcin-szalski** [comment] 2016-07-08 11:05
screenshot attached from a reproduction:
<img width="841" alt="screen shot 2016-07-08 at 11 57 40" src="https://cloud.githubusercontent.com/assets/12157682/16685634/497d58be-4504-11e6-8a11-717a628d062a.png">

**Comment by jllodra** [comment] 2016-07-08 11:15
I believe I know where the problem is.

You have cloned/downloaded the source code instead of downloading the packaged app, haven't you?

cmod can't find the Modarchive API key necessary to make the requests. 

So all I can tell you is:

1) If you have interest in contributing to the source code of cmod, I can share the key with you.
2) If you have no interest in contributing, I recommend you to download the packaged app.

**Comment by marcin-szalski** [comment] 2016-07-08 11:47
sorry to disappoint you, Josep, but I did download the release binary (mentioned in my very first message) and not the source code.

**Comment by jllodra** [comment] 2016-07-08 11:51
Seems that release is messed up. Sorry.

I will check my build system and prepare a new release as soon as possible...

**Comment by jllodra** [comment] 2016-07-08 15:41
Hi again Marcin,

please download the latest release:

https://github.com/jllodra/cmod3/releases/tag/2.1.0d

I think I have fixed the build system.

If you have any other issue or suggestion, feel free to open more issues.
Please note that you can change the download folder for songs from MA in More > Settings.

**Comment by games-neox** [comment] 2016-07-08 19:34
Hi Josep,
now I can confirm the latest release (mentioned in your previous comment) does work much better - Mod Archive operates as expected.
hence this item can be closed as resolved

**Comment by marcin-szalski** [comment] 2016-07-08 19:38
Hi Josep,
now I can confirm the latest release (mentioned in your previous comment) does work much better - Mod Archive operates as expected.
hence this item can be closed as resolved

**Comment by jllodra** [comment] 2016-07-09 09:44
Great

**Closed as completed by jllodra** 2016-07-09 09:44 UTC
